import { useState, type FormEvent } from "react";
import { Navigate, useLocation, useNavigate } from "react-router-dom";
import { authService } from "./services/authService";
import { useAuthStore } from "@/stores/authStore";
import Logo from "@/components/Logo";
import axios from "axios";

type AuthMode = "login" | "register" | "forgot";

export function LoginPage() {
  const navigate = useNavigate(); const location = useLocation(); const setAuth = useAuthStore((state) => state.setAuth); const accessToken = useAuthStore((state) => state.accessToken); const user = useAuthStore((state) => state.user);
  const [mode, setMode] = useState<AuthMode>("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [phone, setPhone] = useState(""); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(false);
  const from = (location.state as { from?: { pathname?: string } } | null)?.from?.pathname ?? "/dashboard";
  if (accessToken && (user?.role === "ADMIN" || user?.role === "STAFF")) return <Navigate to="/dashboard" replace />;
  const changeMode = (next: AuthMode) => { setMode(next); setError(null); setSuccess(null); setPassword(""); };
  const handleSubmit = async (event: FormEvent) => { event.preventDefault(); setError(null); setSuccess(null); setIsLoading(true); try { if (mode === "forgot") { await authService.forgotPassword(email); setSuccess("Nếu email tồn tại, hướng dẫn đặt lại mật khẩu đã được gửi."); return; } const result = mode === "login" ? await authService.login(email, password) : await authService.register(name, email, password, phone || undefined); if (result.user.role !== "ADMIN" && result.user.role !== "STAFF") { await authService.logout(); setError("Tài khoản dashboard phải có quyền admin hoặc staff."); return; } setAuth(result.user, result.accessToken); navigate(from, { replace: true }); } catch (caught: unknown) { const apiMessage = axios.isAxiosError<{ message?: string }>(caught) ? caught.response?.data?.message : undefined; setError(apiMessage ?? (mode === "login" ? "Email hoặc mật khẩu không đúng." : mode === "register" ? "Không thể đăng ký. Email có thể đã tồn tại hoặc dữ liệu không hợp lệ." : "Không thể gửi yêu cầu đặt lại mật khẩu.")); } finally { setIsLoading(false); } };
  const title = mode === "login" ? "Admin Sign In" : mode === "register" ? "Create Admin Account" : "Forgot Password";
  return <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-100 via-white to-slate-200 px-4"><div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><div className="mb-8 flex flex-col items-center gap-3"><Logo /><h1 className="text-xl font-semibold text-slate-900">{title}</h1><p className="text-center text-sm text-slate-500">{mode === "forgot" ? "Nhập email để nhận liên kết đặt lại mật khẩu." : "Use your admin or staff account to manage the store."}</p></div><form onSubmit={(event) => void handleSubmit(event)} className="space-y-4">{mode === "register" && <><Field id="name" label="Name" value={name} onChange={setName} autoComplete="name" /><Field id="phone" label="Phone (optional)" value={phone} onChange={setPhone} autoComplete="tel" /></>}<Field id="email" label="Email" value={email} onChange={setEmail} type="email" autoComplete="email" />{mode !== "forgot" && <Field id="password" label="Password" value={password} onChange={setPassword} type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={8} />}{error && <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{error}</p>}{success && <p className="rounded-md bg-green-50 px-3 py-2 text-sm text-green-700" role="status">{success}</p>}<button type="submit" disabled={isLoading} className="w-full rounded-md bg-slate-900 px-4 py-2.5 text-sm font-medium text-white hover:bg-slate-800 disabled:opacity-60">{isLoading ? "Processing…" : mode === "login" ? "Sign in" : mode === "register" ? "Register" : "Send reset link"}</button></form><div className="mt-5 flex flex-wrap justify-center gap-x-4 gap-y-2 text-sm text-slate-600">{mode !== "login" && <button type="button" onClick={() => changeMode("login")} className="underline">Back to sign in</button>}{mode === "login" && <><button type="button" onClick={() => changeMode("register")} className="underline">Register</button><button type="button" onClick={() => changeMode("forgot")} className="underline">Forgot password?</button></>}</div></div></div>;
}

function Field({ id, label, value, onChange, type = "text", autoComplete, minLength }: { id: string; label: string; value: string; onChange: (value: string) => void; type?: string; autoComplete?: string; minLength?: number }) {
  return <div className="space-y-1.5"><label htmlFor={id} className="text-sm font-medium text-slate-700">{label}</label><input id={id} type={type} autoComplete={autoComplete} required={id !== "phone"} minLength={minLength} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-900 focus:ring-1 focus:ring-slate-900" /></div>;
}
