import { useState, type FormEvent } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import Logo from "@/components/Logo";
import { authService } from "./services/authService";

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(false); const [loading, setLoading] = useState(false); const token = params.get("token") ?? "";
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (!token) { setError("Reset token is missing."); return; } if (password !== confirmation) { setError("Passwords do not match."); return; } setLoading(true); try { await authService.resetPassword(token, password); setSuccess(true); } catch { setError("The reset link is invalid or expired."); } finally { setLoading(false); } };
  return <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-100 via-white to-slate-200 px-4"><div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><div className="mb-8 flex flex-col items-center gap-3"><Logo /><h1 className="text-xl font-semibold text-slate-900">Reset Password</h1></div>{success ? <div className="space-y-4 text-center"><p className="rounded-md bg-green-50 px-3 py-2 text-sm text-green-700" role="status">Password reset successfully.</p><button onClick={() => navigate("/login")} className="w-full rounded-md bg-slate-900 px-4 py-2.5 text-sm text-white">Back to sign in</button></div> : <form onSubmit={(event) => void submit(event)} className="space-y-4"><label className="block space-y-1.5 text-sm font-medium text-slate-700">New password<input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} className="w-full rounded-md border border-slate-300 px-3 py-2 font-normal outline-none focus:border-slate-900 focus:ring-1 focus:ring-slate-900" /></label><label className="block space-y-1.5 text-sm font-medium text-slate-700">Confirm password<input required minLength={8} type="password" autoComplete="new-password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="w-full rounded-md border border-slate-300 px-3 py-2 font-normal outline-none focus:border-slate-900 focus:ring-1 focus:ring-slate-900" /></label>{error && <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{error}</p>}<button disabled={loading} className="w-full rounded-md bg-slate-900 px-4 py-2.5 text-sm text-white disabled:opacity-60">{loading ? "Resetting…" : "Reset password"}</button><Link to="/login" className="block text-center text-sm text-slate-600 underline">Back to sign in</Link></form>}</div></div>;
}
